from testing import Tree,Queue,flexQueue,LinkedList
def test():
    tree = Tree()
    tree.insert(10)
    tree.insert(50)
    tree.insert(3)
    # tree.inorder()
    # tree.isinstence(10)
    assert tree.isinstence(3) == True
    assert tree.isinstence(50) == True
    assert tree.isinstence(100) == False
# test()
def queue():
    queue = Queue(5)
    queue.enqueue(10)
    queue.enqueue(20)
    queue.enqueue(30)
    queue.enqueue(40)
    queue.enqueue(50)
    queue.dequeue()
    queue.dequeue()
    queue.dequeue()
    # queue.getall()
# queue()
def testFlex():
    queue = flexQueue(5)
    queue.enqueue(10)
    queue.enqueue(20)
    queue.enqueue(30)
    queue.enqueue(40)
    queue.enqueue(50)
    queue.enqueue(60)
    queue.enqueue(70)
    queue.enqueue(80)
    queue.enqueue(90)
    queue.enqueue(100)
    queue.enqueue(110)
    queue.dequeue()
    queue.dequeue()
    queue.dequeue()
    queue.dequeue()
    queue.dequeue()
    queue.dequeue()
    queue.dequeue()
    queue.dequeue()
    queue.dequeue()
# testFlex()
def testLL():
    ll = LinkedList()
    ll.insertail(10)
    ll.insertail(20)
    ll.insertail(30)
    ll.insertail(40)
    ll.insertail(50)
    ll.insertail(60)
    ll.insertail(70)
    ll.insertail(80)
    ll.deletbeorelement(50)

    ll.getall()
testLL()