from simpleLinkedList import SimpleLinkedList
def testLL():
    ll = SimpleLinkedList()
    # print(ll.isEmpty())
    ll.insertAtHead(10)
    ll.insertAtHead(20)
    ll.insertAtEnd(100)
    ll.insertAtHead(30)
    ll.getLL()
    ll.isMember(100)
    print('-------------')
    # ll.getLL()
    print(f'removed {ll.removeFromTail()}')
    ll.getLL()
    # print(f'removed {ll.removeFromTail()}')
    # ll.getLL()
    # print(f'removed {ll.removeFromTail()}')
    print('-------------')
    ll.getLL()
testLL()