from simpleQueue import fixQueue,infQueue
def testFixQueue():
    queue = fixQueue(5)
    queue.enqueue(1)
    queue.enqueue(2)
    queue.enqueue(3)
    queue.enqueue(4)
    queue.enqueue(5)
    queue.dequeue()
    queue.enqueue(6)
    queue.dequeue()
    queue.dequeue()
    queue.enqueue(5)
    queue.enqueue(6)
    queue.enqueue(8)
    queue.dequeue()
# testFixQueue()

def testInf():
    queue = infQueue()
    queue.enqueue(1) 
    queue.enqueue(2) 
    queue.enqueue(3) 
    queue.enqueue(4) 
    queue.enqueue(5) 
    queue.dequeue() 
    queue.enqueue(6) 
    queue.enqueue(6) 
    queue.enqueue(6) 
    queue.enqueue(6) 
    queue.enqueue(7) 
    queue.enqueue(7) 
    queue.enqueue(7) 
    queue.dequeue() 
    queue.dequeue() 
    queue.dequeue() 
    queue.dequeue() 
    queue.dequeue() 
    queue.dequeue() 
    queue.dequeue() 
    queue.dequeue() 
    queue.dequeue() 
    queue.dequeue() 
    queue.dequeue() 
    queue.dequeue() 
testInf()